export const userConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',
};

export const menuConstants = {
  CHANGEOPENKEYS: 'CHANGEOPENKEYS',
  CHANGEPATH: 'CHANGEPATH',
  TOGGLEMENULEFT: 'TOGGLEMENU',
  TOGGLEMENURIGHT: 'TOGGLEMENURIGHT',
  GETMENURIGHT: 'GETMENURIGHT',
  REQUEST: 'GETMENULIST_REQUEST',
  SUCCESS: 'GETMENULIST_SUCCESS',
  FAILURE: 'GETMENULIST_FAILURE',
}

export const alertConstants = {
  SUCCESS: 'ALERT_SUCCESS',
  ERROR: 'ALERT_ERROR',
  CLEAR: 'ALERT_CLEAR'
};

export const ledgerConstants = {
  GET_PREFIX_REQUEST: 'GET_PREFIX_REQUEST',
  GET_PREFIX_SUCCESS: 'GET_PREFIX_SUCCESS',
  GET_PREFIX_FAILURE: 'GET_PREFIX_FAILURE',
  GET_PAGE: 'GET_PAGE'
};





